// Code generated by Slice Machine. DO NOT EDIT.

import Gallery from "./Gallery/index.svelte";
import WorkDescription from "./WorkDescription/index.svelte";
import WorkHero from "./WorkHero/index.svelte";

export const components = {
  gallery: Gallery,
  work_description: WorkDescription,
  work_hero: WorkHero,
};
